<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <title>Client</title>
</head>
<body class="container">

    <nav>
        <a href="?action=client">Client</a>
        <a href="?action=commande">Commande</a>
    </nav>

    <h1 class="text-center">Commande</h1>
    <form>
        <div class="mb-3">
            <select name="" id="">
                <option value="">Toto</option>
                <option value="">Tatat</option>
            </select>
        </div>
        <div class="mb-3">
            <select name="" id="">
                <option value="">PC</option>
                <option value="">Clavier</option>
            </select>
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    
</body>
</html>